easy_admin:
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - name
                    - description
                    - price
                    - isPublished
                    - imageName
                    - category
                    - publisher
            list:
                fields: [name, isPublished, category, publisher]
        Category:
          class: App\Entity\Category
        User:
            class: App\Entity\User
        Tag:
          class: App\Entity\Tag
