vich_uploader:
    db_driver: orm

    mappings:
        # Nom du mapping
        miniature_produit:
            uri_prefix: /uploads/product
            # Dossier d'upload
            upload_destination: '%kernel.project_dir%/public/uploads/product'
